arrowParens: "avoid"
bracketSpacing: true
insertPragma: true
jsxBracketSameLine: false
parser: "babylon"
printWidth: 120
requirePragma: true
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "none"
useTabs: true