const ACTIONS = {
  EXAMPLE_ERROR: 'EXAMPLE_ERROR',
  EXAMPLE_ERROR_DATA: 'EXAMPLE_ERROR_DATA',
  EXAMPLE_IS_LOADING: 'EXAMPLE_IS_LOADING',
  EXAMPLE_SUCCESS: 'EXAMPLE_SUCCESS'
}

export default ACTIONS;
