const ACTIONS = {
  FIRST_GLOBAL_LOADING: 'FIRST_GLOBAL_LOADING',
  FIRST_GLOBAL_ERROR: 'FIRST_GLOBAL_ERROR',
  FIRST_GLOBAL_SUCCESS: 'FIRST_GLOBAL_SUCCESS',

  SECOND_GLOBAL_LOADING: 'SECOND_GLOBAL_LOADING',
  SECOND_GLOBAL_ERROR: 'SECOND_GLOBAL_ERROR',
  SECOND_GLOBAL_SUCCESS: 'SECOND_GLOBAL_SUCCESS',
};

export default ACTIONS;
